sonar.projectKey=ClassIQ
sonar.projectName=ClassIQ
sonar.projectVersion=1.0

sonar.sources=ClassIQ_codes/src/main/java
sonar.tests=ClassIQ_codes/src/test/java
sonar.java.binaries=ClassIQ_codes/target/classes
sonar.junit.reportPaths=ClassIQ_codes/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=ClassIQ_codes/target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/frontend/**,**/backend/model/dao/**,**/backend/db/**
sonar.coverage.exclusions=**/frontend/**,**/backend/model/dao/**,**/backend/db/**