pipeline {
    agent any

    tools {
        jdk 'JDK 21'
        maven 'Maven_3'
    }

    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        DOCKERHUB_CREDENTIALS_ID = 'Docker_Hub'
        DOCKERHUB_REPO = 'roshinif/classiq'
        DOCKER_IMAGE_TAG = 'latest'
        PROJECT_DIR = 'ClassIQ_codes'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                        url: 'https://github.com/Tharushika78910/ClassIQ.git'
            }
        }

        stage('Build') {
            steps {
                dir('ClassIQ_codes') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('ClassIQ_codes') {
                    bat 'mvn test'
                }
            }
        }

        stage('JaCoCo Report') {
            steps {
                dir('ClassIQ_codes') {
                    bat 'mvn jacoco:report'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'ClassIQ_codes/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage Report') {
            steps {
                publishHTML([
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'ClassIQ_codes/target/site/jacoco',
                        reportFiles: 'index.html',
                        reportName: 'JaCoCo Coverage Report'
                ])
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}", "ClassIQ_codes")
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', DOCKERHUB_CREDENTIALS_ID) {
                        def img = docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                        img.push()
                    }
                }
            }
        }
    }
}