pipeline {
    agent any

    tools {
        jdk 'JDK 21'
        maven 'Maven_3'
    }

    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        DOCKERHUB_CREDENTIALS_ID = 'Docker_Hub'
        DOCKERHUB_REPO = 'poornimj/classiq'
        DOCKER_IMAGE_TAG = "${BUILD_NUMBER}"
        PROJECT_DIR = 'ClassIQ_codes'
        SONARQUBE_ENV = 'SonarQubeServer'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main',
                        url: 'https://github.com/Tharushika78910/ClassIQ.git'
            }
        }

        stage('Build, Test and Coverage') {
            steps {
                dir("${PROJECT_DIR}") {
                    bat 'mvn clean verify'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'ClassIQ_codes/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage Report') {
            steps {
                publishHTML([
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'ClassIQ_codes/target/site/jacoco',
                        reportFiles: 'index.html',
                        reportName: 'JaCoCo Coverage Report'
                ])
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv("${SONARQUBE_ENV}") {
                    dir("${PROJECT_DIR}") {
                        bat 'mvn sonar:sonar -Dsonar.projectKey=ClassIQ -Dsonar.projectName=ClassIQ'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}", "ClassIQ_codes")
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push('latest')
                    }
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                bat '''
                docker rm -f classiq-container
                exit /b 0
                '''
                bat """
                docker run -d --name classiq-container -p 8080:8080 ^
                -v C:\\classiq-reports:/app/reports ^
                -e DB_HOST=host.docker.internal ^
                -e DB_PORT=3306 ^
                -e DB_NAME=classiq ^
                -e DB_USER=root ^
                -e DB_PASS=root123 ^
                ${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}
                """
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'ClassIQ_codes/target/*.jar', fingerprint: true
        }
    }
}